name: the_widget_marker
description: A package to convert Widget, Local image, Netwok image, Svg file to BitmapDescriptor which can be used in google_maps_flutter icon marker.
version: 1.0.0
homepage: https://github.com/therif/the_widget_marker

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  google_maps_flutter: ^2.4.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
